# Generated by Django 5.0.6 on 2024-05-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='No description provided', verbose_name='No description provided'),
            preserve_default=False,
        ),
    ]
